### PR TITLE
Add support for delegation and return values with @yieldfrom

### LINKED ISSUE #49: Delegating to subgenerator (PEP 380)
In Python the `yield from` syntax described in [PEP 380](https://www.python.org/dev/peps/pep-0380/) allows a generator to delegate to a subgenerator, with the subgenerator then able to yield to the caller of the original generator. This is useful for factoring code out of more complex generator functions, and when working with recursive generator functions.

Would it be possible to support delegation like this in ResumableFunctions.jl?

### PR DESCRIPTION
**Pull request by gerlero**
This is a basic implementation of delegation to a subgenerator inspired by [PEP 380](https://peps.python.org/pep-0380/). Delegation with a plain ``@yieldfrom iter`` expression (i.e., no assignment on the left) should work for any iterable, while ``arg = @yieldfrom f`` requires that `f` is actually a `@resumable` function, as I didn't find a standard mechanism for iterators to "return" values. Note that in the latter case, `arg` will be assigned the return value of `f`: this also means that it now makes sense for a `@resumable` function to also return a value, so I've removed the warning for this case.

Closes #49 

EDITS: `@yield_from` -> `@yieldfrom` (https://github.com/QuantumSavory/Semicoroutines.jl/pull/8), typo

### CODE REVIEW

**Comment by Krastanov** [comment]
I believe Ben, the original author, might not have the bandwidth to work on ResumableFunctions these days. Thus, I forked the repository into a new Semicoroutines.jl https://github.com/QuantumSavory/Semicoroutines.jl in order to support 1.10 and future julia versions.

@gerlero  , could you consider making this pull request against the fork?

As this library is an important part of another project of mine, I plan to provide support at least for the next few years. I am certainly interested in having help from other contributors (and maybe merging things back here if ResumableFunctions.jl is revided).

A similar fork is being prepared for SimJulia

**Comment by gerlero** [comment]
Sure enough. Thanks! I'll open the same PR against Semicoroutines.jl

**Comment by BenLauwens** [comment]
Please resolve conflicts so that this can be merged.

**Comment by Krastanov** [comment]
@gerlero , give me a few hours to fix the tests, so we have JET and Aqua available. That might also already fix most of the merge conflicts.

**Comment by gerlero** [comment]
@Krastanov Let me know when I can start working on the merge conflicts for this one.

**Comment by Krastanov** [comment]
Please go ahead! Tests and CI are already updated.

**Comment by Krastanov** [comment]
I guess we need to decide whether to drop support for Julia 1.2... The current LTS is 1.6, anything older is not really supported upstream either.

**Comment by hdavid16** [comment]
I support dropping it. I would go with LTS and up.

**Comment by Krastanov** [comment]
Let's wait until next week when we will have a more extended discussion with Ben and bring it up then. I am also in favor of dropping pre-1.6 versions.

**Comment by gerlero** [comment]
> In the meantime could you go ahead and modify the project.toml (to increase to julia 1.6 and to bump the version number for the package) and add a quick description to README in the change log section?

Done. I've bumped just the patch component (to v0.6.3), pending/following discussion at #63, but it's up to you and others if you think this should get a different version number (e.g. 0.7 or 1.0).

**Comment by Krastanov** [comment]
all the cleanup from the move is now finished, so I am merging this. Thanks for the contribution!!!

**Comment by gerlero** [comment]
@Krastanov thank you!

**Pull request merged**
