### PR TITLE
Adjust to upcoming julia#54341

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by Krastanov** [comment]
@Keno , I was a bit too trigger happy to merge this -- does it actually fix anything? There is no `src` in this function, so I expect to just get an undefined variable error here.

**Comment by Keno** [comment]
Sorry, should be `ci` of course. I must have gotten myself confused with another package.

**Comment by Krastanov** [comment]
And just to double check, any reason it is not `@static if ...`? Not quite sure what are the rules here

**Comment by Keno** [comment]
`@static` is fine, but shouldn't be required. The feature check will const fold, but even if it didn't, it's on the compile-time path, so it runs infrequently. Generally I don't use `@static` unless there's some reason it's needed

**Comment by Krastanov** [comment]
noted, thanks!

**Pull request merged**
