### PR TITLE
Revert "run inference in generated function (#76)"

### LINKED ISSUE #80: ResumableFunctions v0.6.6 StackOverflow with julia-1.10
My package https://github.com/marcom/FoldRNA.jl/ uses ResumableFunctions for the function `allstruct`.

https://github.com/marcom/FoldRNA.jl/blob/main/src/allstruct.jl

On julia-1.10 and with ResumableFunctions 0.6.6, I get a StackOverflow with a neverending(?) stacktrace from julia internals. Only `kill -9` seems to stop the process in reasonable time.

With ResumableFunctions v0.6.5 everything works as expected, so I am releasing a new version of FoldRNA now keeping ResumableFunctions at v0.6.5 in compat.

To reproduce:
```
# ensure ResumableFunctions compat is set to =0.6.6
using FoldRNA
collect(allstruct(10))
```

<details>
<summary>Output for julia-1.10, ResumableFunctions v0.6.6</summary>

```
Internal error: encountered unexpected error during compilation of show:
StackOverflowError()
emit_expr at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/codegen.cpp:5421
emit_call at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/codegen.cpp:4569
emit_expr at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/codegen.cpp:5511
emit_ssaval_assign at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/codegen.cpp:5101
emit_stmtpos at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/codegen.cpp:5335 [inlined]
emit_function at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/codegen.cpp:8380
jl_emit_code at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/codegen.cpp:8715
jl_emit_codeinst at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/codegen.cpp:8789
_jl_compile_codeinst at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/jitlayers.cpp:221
jl_generate_fptr_impl at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/jitlayers.cpp:518
jl_compile_method_internal at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2480 [inlined]
jl_compile_method_internal at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2368
_jl_invoke at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2886 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:3076
print at ./boot.jl:584
jfptr_print_25803.1 at /home/mcm/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:3076
println at ./boot.jl:587
println at ./boot.jl:591
jfptr_println_25813.1 at /home/mcm/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:3076
fsmi_generator at /home/mcm/.julia/packages/ResumableFunctions/kJXjK/src/utils.jl:153
unknown function (ip: 0x7f905211789c)
_jl_invoke at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:3076
jl_call_staged at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/method.c:540
ijl_code_for_staged at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/method.c:593
get_staged at ./compiler/utilities.jl:123
retrieve_code_info at ./compiler/utilities.jl:135 [inlined]
InferenceState at ./compiler/inferencestate.jl:430
typeinf_edge at ./compiler/typeinfer.jl:920
abstract_call_method at ./compiler/abstractinterpretation.jl:629
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:95
abstract_call_known at ./compiler/abstractinterpretation.jl:2083
abstract_call at ./compiler/abstractinterpretation.jl:2165
abstract_call at ./compiler/abstractinterpretation.jl:2158
abstract_call at ./compiler/abstractinterpretation.jl:2350
abstract_eval_call at ./compiler/abstractinterpretation.jl:2366
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2376
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2620
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2885
typeinf_local at ./compiler/abstractinterpretation.jl:3094
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3182
_typeinf at ./compiler/typeinfer.jl:247
typeinf at ./compiler/typeinfer.jl:216
typeinf_edge at ./compiler/typeinfer.jl:930
abstract_call_method at ./compiler/abstractinterpretation.jl:629
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:95
abstract_call_known at ./compiler/abstractinterpretation.jl:2083
abstract_call at ./compiler/abstractinterpretation.jl:2165
abstract_call at ./compiler/abstractinterpretation.jl:2158
abstract_call at ./compiler/abstractinterpretation.jl:2350
abstract_eval_call at ./compiler/abstractinterpretation.jl:2366
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2376
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2620
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2885
typeinf_local at ./compiler/abstractinterpretation.jl:3094
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3182
_typeinf at ./compiler/typeinfer.jl:247
typeinf at ./compiler/typeinfer.jl:216
typeinf_frame at ./compiler/typeinfer.jl:995
#code_typed_by_type#11 at /home/mcm/.julia/packages/ResumableFunctions/kJXjK/src/utils.jl:139
code_typed_by_type at /home/mcm/.julia/packages/ResumableFunctions/kJXjK/src/utils.jl:131 [inlined]
fsmi_generator at /home/mcm/.julia/packages/ResumableFunctions/kJXjK/src/utils.jl:151
unknown function (ip: 0x7f905211789c)
_jl_invoke at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:2894 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/gf.c:3076
jl_call_staged at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/method.c:540
ijl_code_for_staged at /cache/build/builder-amdci4-6/julialang/julia-release-1-dot-10/src/method.c:593
get_staged at ./compiler/utilities.jl:123
retrieve_code_info at ./compiler/utilities.jl:135 [inlined]
InferenceState at ./compiler/inferencestate.jl:430
typeinf_edge at ./compiler/typeinfer.jl:920
abstract_call_method at ./compiler/abstractinterpretation.jl:629
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:95
abstract_call_known at ./compiler/abstractinterpretation.jl:2083
abstract_call at ./compiler/abstractinterpretation.jl:2165
abstract_call at ./compiler/abstractinterpretation.jl:2158
abstract_call at ./compiler/abstractinterpretation.jl:2350
abstract_eval_call at ./compiler/abstractinterpretation.jl:2366
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2376
[... continues seemingly endlessly ...]
```

</details>

### PR DESCRIPTION
**Pull request by gerlero**
Reverts #76 due to #80.

@Krastanov @pepijndevos @marcom

EDIT: Fixes #80

### CODE REVIEW

**Comment by gerlero** [comment]
`@yieldfrom` is failing CI on Julia nightly but that looks like a different issue.

@marcom's code from #80 no longer fails with this branch, so I'll merge it soon unless someone objects.

**Comment by Krastanov** [comment]
Thanks for taking care of this! Could we give some time to Pepijn to respond with his plans, as he spearheaded these past improvements (and they are quite valuable)? It is holiday season right now so things can be a bit slow. If it is a quick fix we can just wait for that. If it is something he does not have the bandwidth for (perfectly understandable given that it is all volunteer efforts by everyone here), or if it is something that would take a while, we should proceed with this reversal.

However, could you please preserve the tests and mark them as `@test_broken`? Even if we have to revert #76, we should not lose track of the issues Pepijn reported.

**Comment by Krastanov** [comment]
Apologies, I did not see the message Pepijn had posted on the other thread. Could you please preserve the tests (now `@test_broken`) and I am happy to vote in favor of this being merged and released.

**Comment by gerlero** [comment]
> Could you please preserve the tests (now `@test_broken`)

Good call.

> and I am happy to vote in favor of this being merged and released

Thanks. I'll take care of that and release a new patch version.

**Pull request merged**
